SST: SST::IMPL::Partition::SimplePartitioner Class Reference
SST::IMPL::Partition::SimplePartitioner Class Reference
Public Member Functions
RankInfo convertPartNum (uint32_t partNum)
void simple_partition_step (PartitionComponentMap_t &component_map, ComponentId_t *setA, const int lengthA, int rankA, ComponentId_t *setB, const int lengthB, int rankB, std::map< ComponentId_t, std::map< ComponentId_t, SimTime_t > *> timeTable, int step)
SimplePartitioner (RankInfo total_ranks, RankInfo my_rank, int verbosity)
void performPartition (PartitionGraph *graph) override
Function to be overridden by subclasses.
bool requiresConfigGraph () override
bool spawnOnAllRanks () override
Public Member Functions inherited from SST::Partition::SSTPartitioner
virtual void performPartition (PartitionGraph *UNUSED(graph))
Function to be overridden by subclasses.
virtual void performPartition (ConfigGraph *UNUSED(graph))
Function to be overridden by subclasses.
virtual void performPartition (ConfigGraph *graph)
Function to be overridden by subclasses.
Data Fields
SST_ELI_REGISTER_PARTITIONER(SimplePartitioner, "sst", "simple", SST_ELI_ELEMENT_VERSION(1, 0, 0), "Simple partitioning scheme which attempts to partition on high latency links " "while balancing number of components per rank.") private uint32_t total_parts
Member Function Documentation
performPartition()
void SST::IMPL::Partition::SimplePartitioner::performPartition (PartitionGraph * graph) override virtual
Function to be overridden by subclasses.
Performs the partitioning of the Graph using the PartitionGraph object.
Result of this function is that every ConfigComponent in graph has a Rank applied to it.
Reimplemented from SST::Partition::SSTPartitioner.
References SST::SparseVectorMap< keyT, classT >::begin(), SST::SparseVectorMap< keyT, classT >::end(), SST::PartitionLink::getMinLatency(), and SST::SparseVectorMap< keyT, classT >::insert().
The documentation for this class was generated from the following files:
src/sst/core/impl/partitioners/simplepart.h
src/sst/core/impl/partitioners/simplepart.cc