SST: SST::Statistics::Statistic< void > Class Template Reference
SST::Statistics::Statistic< void > Class Template Reference
void Statistic has special meaning in that it does not collect fields in the usual way through the addData function.
#include <statbase.h>
Public Member Functions
SST_ELI_DECLARE_INFO (ELI::ProvidesInterface, ELI::ProvidesParams) void registerOutputFields(StatisticFieldsOutput *statOutput) override
void outputStatisticFields (StatisticFieldsOutput *statOutput, bool EndOfSimFlag) override
Called by the system to tell the Statistic to send its data to the StatisticOutput to be output.
Public Member Functions inherited from SST::Statistics::StatisticBase
void enable ()
Enable Statistic for collections.
void disable ()
Disable Statistic for collections.
virtual void clearStatisticData ()
Inform the Statistic to clear its data.
virtual void resetCollectionCount ()
Set the current collection count to 0.
virtual void incrementCollectionCount (uint64_t increment)
Increment current collection count.
virtual void setCollectionCount (uint64_t newCount)
Set the current collection count to a defined value.
virtual void setCollectionCountLimit (uint64_t newLimit)
Set the collection count limit to a defined value.
void setFlagResetCountOnOutput (bool flag)
Set the Reset Count On Output flag.
void setFlagClearDataOnOutput (bool flag)
Set the Clear Data On Output flag.
void setFlagOutputAtEndOfSim (bool flag)
Set the Output At End Of Sim flag.
const std::string & getCompName () const
Return the Component Name.
const std::string & getStatName () const
Return the Statistic Name.
const std::string & getStatSubId () const
Return the Statistic SubId.
const std::string & getFullStatName () const
Return the full Statistic name of Component.StatName.SubId.
const std::string & getStatTypeName () const
Return the Statistic type name.
const StatisticFieldInfo::fieldType_t & getStatDataType () const
Return the Statistic data type.
const char * getStatDataTypeShortName () const
Return the Statistic data type.
const char * getStatDataTypeFullName () const
Return the Statistic data type.
BaseComponent * getComponent () const
Return a pointer to the parent Component.
bool isEnabled () const
Return the enable status of the Statistic.
bool isOutputEnabled () const
Return the enable status of the Statistic's ability to output data.
uint64_t getCollectionCountLimit () const
Return the collection count limit.
uint64_t getCollectionCount () const
Return the current collection count.
bool getFlagResetCountOnOutput () const
Return the ResetCountOnOutput flag value.
bool getFlagClearDataOnOutput () const
Return the ClearDataOnOutput flag value.
bool getFlagOutputAtEndOfSim () const
Return the OutputAtEndOfSim flag value.
StatMode_t getRegisteredCollectionMode () const
Return the collection mode that is registered.
void delayOutput (const char *delayTime)
Delay the statistic from outputting data for a specified delay time.
void delayCollection (const char *delayTime)
Delay the statistic from collecting data for a specified delay time.
virtual bool isReady () const
Indicate that the Statistic is Ready to be used.
virtual bool isNullStatistic () const
Indicate if the Statistic is a NullStatistic.
Protected Member Functions
Statistic (BaseComponent *comp, const std::string &statName, const std::string &statSubId, Params &statParams)
Construct a Statistic.
Protected Member Functions inherited from SST::Statistics::StatisticBase
StatisticBase (BaseComponent *comp, const std::string &statName, const std::string &statSubId, Params &statParams)
Construct a StatisticBase.
Params & getParams ()
Return the Statistic Parameters.
void setStatisticDataType (const StatisticFieldInfo::fieldType_t dataType)
Set the Statistic Data Type.
void setStatisticTypeName (const char *typeName)
Set an optional Statistic Type Name.
Friends
class SST::Factory
class SST::BaseComponent
Additional Inherited Members
Public Types inherited from SST::Statistics::StatisticBase
enum StatMode_t { STAT_MODE_UNDEFINED, STAT_MODE_COUNT, STAT_MODE_PERIODIC, STAT_MODE_DUMP_AT_END }
Statistic collection mode.
Static Public Member Functions inherited from SST::Statistics::StatisticBase
static const std::vector< ElementInfoParam > & ELI_getParams ()
Detailed Description
template<>
class SST::Statistics::Statistic< void >
void Statistic has special meaning in that it does not collect fields in the usual way through the addData function.
It has to use custom functions.
Constructor & Destructor Documentation
Statistic()
SST::Statistics::Statistic< void >::Statistic (BaseComponent * comp, const std::string & statName, const std::string & statSubId, Params & statParams) inline protected
Construct a Statistic.
Parameters
comp - Pointer to the parent constructor.
statName - Name of the statistic to be registered. This name must match the name in the ElementInfoStatistic.
statSubId - Additional name of the statistic
statParams - The parameters for this statistic
Member Function Documentation
outputStatisticFields()
void SST::Statistics::Statistic< void >::outputStatisticFields (StatisticFieldsOutput * statOutput, bool EndOfSimFlag) override virtual
Called by the system to tell the Statistic to send its data to the StatisticOutput to be output.
Parameters
statOutput - Pointer to the statistic output
EndOfSimFlag - Indicates that the output is occurring at the end of simulation.
Implements SST::Statistics::StatisticBase.
References SST::Output::fatal(), SST::Statistics::StatisticBase::getComponent(), SST::Statistics::StatisticBase::getFullStatName(), SST::Simulation_impl::getSimulation(), SST::Simulation_impl::getSimulationOutput(), and SST::Statistics::StatisticBase::getStatTypeName().
The documentation for this class was generated from the following files:
src/sst/core/statapi/statbase.h
src/sst/core/statapi/statbase.cc