SST: SST::TimeConverter Class Reference
SST::TimeConverter Class Reference
A class to convert between a component's view of time and the core's view of time.
#include <timeConverter.h>
Public Member Functions
SimTime_t convertToCoreTime (SimTime_t time) const
Converts from the component's view to the core's view of time.
SimTime_t convertFromCoreTime (SimTime_t time) const
Converts from the core's view to the components's view of time.
SimTime_t getFactor () const
Return the factor used for conversions with Core Time.
UnitAlgebra getPeriod () const
Return the period represented by this TimeConverter as a UnitAlgebra.
Friends
class TimeLord
Detailed Description
A class to convert between a component's view of time and the core's view of time.
Member Function Documentation
convertFromCoreTime()
SimTime_t SST::TimeConverter::convertFromCoreTime (SimTime_t time) const inline
Converts from the core's view to the components's view of time.
The result is truncated, not rounded.
Parameters
time time to convert from core time
Referenced by SST::BaseComponent::getCurrentSimTime(), SST::BaseComponent::getCurrentSimTimeMicro(), SST::BaseComponent::getCurrentSimTimeMilli(), and SST::BaseComponent::getCurrentSimTimeNano().
convertToCoreTime()
SimTime_t SST::TimeConverter::convertToCoreTime (SimTime_t time) const inline
Converts from the component's view to the core's view of time.
Parameters
time time to convert to core time
Referenced by SST::Link::addRecvLatency(), SST::Link::addSendLatency(), and SST::Link::send().
The documentation for this class was generated from the following files:
src/sst/core/timeConverter.h
src/sst/core/timeLord.cc