SST: SST::Core::SSTPythonModelDefinition Class Reference
SST::Core::SSTPythonModelDefinition Class Reference
Public Member Functions
ConfigGraph * createConfigGraph () override
Create the ConfigGraph.
Config * getConfig (void) const
bool setConfigEntryFromModel (const std::string &entryName, const std::string &value)
ConfigGraph * getGraph (void) const
Output * getOutput () const
ComponentId_t getNextComponentId ()
ComponentId_t addComponent (const char *name, const char *type)
ConfigComponent * findComponentByName (const char *name) const
ConfigComponentMap_t & components ()
void addLink (ComponentId_t id, const char *link_name, const char *port, const char *latency, bool no_cut) const
void setLinkNoCut (const char *link_name) const
void pushNamePrefix (const char *name)
void popNamePrefix (void)
char * addNamePrefix (const char *name) const
void setStatisticOutput (const char *Name)
void addStatisticOutputParameter (const std::string &param, const std::string &value)
void setStatisticLoadLevel (uint8_t loadLevel)
void addGlobalParameter (const char *set, const char *key, const char *value, bool overwrite)
UnitAlgebra getElapsedExecutionTime () const
UnitAlgebra getLocalMemoryUsage () const
void setCallPythonFinalize (bool state)
Public Member Functions inherited from SST::SSTModelDescription
SSTModelDescription (Config *cfg)
Protected Member Functions
void initModel (const std::string &script_file, int verbosity, Config *config, int argc, char **argv)
Protected Member Functions inherited from SST::SSTModelDescription
bool setOptionFromModel (const std::string &entryName, const std::string &value)
Set a configuration string to update configuration values.
void setModelOptions (const std::string &options)
Sets the model options field of the Config object.
void insertGlobalParameter (const std::string &set, const Params::key_type &key, const Params::key_type &value, bool overwrite=true)
Allows ModelDefinition to set global parameters.
Protected Attributes
std::string scriptName
Output * output
Config * config
ConfigGraph * graph
char * namePrefix
size_t namePrefixLen
std::vector< size_t > nameStack
std::map< std::string, ComponentId_t > compNameMap
ComponentId_t nextComponentId
double start_time
bool callPythonFinalize
Member Function Documentation
createConfigGraph()
ConfigGraph * SSTPythonModelDefinition::createConfigGraph () override virtual
Create the ConfigGraph.
This function should be overridden by subclasses.
This function is responsible for reading any configuration files and generating a ConfigGraph object.
Implements SST::SSTModelDescription.
References SST::Output::fatal(), and SST::Output::verbose().
Referenced by SST::Core::SSTXmlModelDefinition::createConfigGraph().
The documentation for this class was generated from the following files:
src/sst/core/model/python/pymodel.h
src/sst/core/model/python/pymodel.cc