SST: SST::TimeLord Class Reference
SST::TimeLord Class Reference
Class for creating and managing TimeConverter objects.
#include <timeLord.h>
Public Member Functions
TimeConverter * getTimeConverter (const std::string &ts)
Create a new TimeConverter object using specified SI Units.
TimeConverter * getTimeConverter (const UnitAlgebra &ts)
Create a new TimeConverter object using the specified units.
UnitAlgebra getTimeBase () const
Return the Time Base of the TimeLord.
TimeConverter * getNano ()
Return a TimeConverter which represents Nanoseconds.
TimeConverter * getMicro ()
Return a TimeConverter which represents Microseconds.
TimeConverter * getMilli ()
Return a TimeConverter which represents Milliseconds.
SimTime_t getSimCycles (const std::string &timeString, const std::string &where)
Not a Public API.
Friends
class SST::Simulation
class SST::Simulation_impl
class SST::Link
Detailed Description
Class for creating and managing TimeConverter objects.
Member Function Documentation
getSimCycles()
SimTime_t SST::TimeLord::getSimCycles (const std::string & timeString, const std::string & where)
Not a Public API.
Returns the number of raw simulation cycles given by a specified time string
References SST::TimeConverter::getFactor(), and getTimeConverter().
Referenced by SST::Link::addRecvLatency(), SST::Link::addSendLatency(), and SST::Simulation_impl::setStopAtCycle().
getTimeConverter() [1/2]
TimeConverter * SST::TimeLord::getTimeConverter (const std::string & ts)
Create a new TimeConverter object using specified SI Units.
For example, "1 Ghz" (1 Gigahertz), "2.5 ns" (2.5 nanoseconds).
Parameters
ts String indicating the base unit for this object. The string should be a floating point number followed by a prefix, and then frequency (i.e. Hz) or time unit (s). Allowable seconds prefixes are: 'f' (fempto), 'p' (pico), 'n' (nano), 'u' (micro), 'm' (milli). Allowable frequency prefixes are 'k' (kilo), 'M' (mega), and 'G' (giga).
Referenced by SST::BaseComponent::getCurrentSimTime(), SST::Link::getDefaultTimeBase(), getSimCycles(), getTimeConverter(), SST::Simulation_impl::registerClock(), and SST::BaseComponent::registerTimeBase().
getTimeConverter() [2/2]
TimeConverter * SST::TimeLord::getTimeConverter (const UnitAlgebra & ts)
Create a new TimeConverter object using the specified units.
Parameters
ts UnitAlgebra object indicating the base unit for this object.
References SST::Output::fatal(), SST::UnitAlgebra::getRoundedValue(), getTimeConverter(), SST::UnitAlgebra::getValue(), SST::UnitAlgebra::hasUnits(), SST::UnitAlgebra::invert(), and SST::UnitAlgebra::toStringBestSI().
The documentation for this class was generated from the following files:
src/sst/core/timeLord.h
src/sst/core/timeLord.cc