SST: SST::Statistics::StatisticOutputCSV Class Reference
SST::Statistics::StatisticOutputCSV Class Reference
The class for statistics output to a comma separated file.
#include <statoutputcsv.h>
Public Member Functions
SST_ELI_REGISTER_DERIVED (StatisticOutput, StatisticOutputCSV, "sst", "statoutputcsv", SST_ELI_ELEMENT_VERSION(1, 0, 0), "Output directly to console screen") StatisticOutputCSV(Params &outputParameters)
Construct a StatOutputCSV.
Public Member Functions inherited from SST::Statistics::StatisticFieldsOutput
void registerStatistic (StatisticBase *stat) override
void output (StatisticBase *statistic, bool endOfSimFlag) override
void startOutputGroup (StatisticGroup *group) override
void stopOutputGroup () override
void startRegisterGroup (StatisticGroup *group) override
void stopRegisterGroup () override
StatisticFieldInfo * getRegisteredField (fieldHandle_t fieldHandle)
Adjust the hierarchy of the fields (FUTURE SUPPORT)
template<typename T >
StatisticFieldInfo * getRegisteredField (const char *statisticName, const char *fieldName)
Return the information on a registered field via known names.
FieldInfoArray_t & getFieldInfoArray ()
Return the array of registered field infos.
virtual void outputField (fieldHandle_t fieldHandle, int32_t data)
Output field data.
virtual void outputField (fieldHandle_t fieldHandle, uint32_t data)
virtual void outputField (fieldHandle_t fieldHandle, int64_t data)
virtual void outputField (fieldHandle_t fieldHandle, uint64_t data)
virtual void outputField (fieldHandle_t fieldHandle, float data)
virtual void outputField (fieldHandle_t fieldHandle, double data)
template<typename T >
fieldHandle_t registerField (const char *fieldName)
Register a field to be output (templated function)
const char * getFieldTypeShortName (fieldType_t type)
Output field data.
Public Member Functions inherited from SST::Statistics::StatisticOutput
std::string & getStatisticOutputName ()
Return the Statistic Output name.
Params & getOutputParameters ()
Return the parameters for the StatisticOutput.
virtual bool acceptsGroups () const
True if this StatOutput can handle StatisticGroups.
virtual bool supportsDynamicRegistration () const
Protected Member Functions
bool checkOutputParameters () override
Perform a check of provided parameters.
void printUsage () override
Print out usage for this Statistic Output.
void startOfSimulation () override
Indicate to Statistic Output that simulation started.
void endOfSimulation () override
Indicate to Statistic Output that simulation ended.
void implStartOutputEntries (StatisticBase *statistic) override
Implementation function for the start of output.
void implStopOutputEntries () override
Implementation function for the end of output.
void outputField (fieldHandle_t fieldHandle, int32_t data) override
Implementation functions for output.
void outputField (fieldHandle_t fieldHandle, uint32_t data) override
void outputField (fieldHandle_t fieldHandle, int64_t data) override
void outputField (fieldHandle_t fieldHandle, uint64_t data) override
void outputField (fieldHandle_t fieldHandle, float data) override
void outputField (fieldHandle_t fieldHandle, double data) override
Protected Member Functions inherited from SST::Statistics::StatisticFieldsOutput
StatisticFieldsOutput (Params &outputParameters)
Construct a base StatisticOutput.
virtual void startRegisterFields (StatisticBase *statistic)
These can be overriden, if necessary, but must be callable by the derived class.
virtual void stopRegisterFields ()
virtual void startOutputEntries (StatisticBase *statistic)
virtual void stopOutputEntries ()
Protected Member Functions inherited from SST::Statistics::StatisticOutput
StatisticOutput (Params &outputParameters)
Construct a base StatisticOutput.
void setStatisticOutputName (const std::string &name)
void lock ()
void unlock ()
Additional Inherited Members
Public Types inherited from SST::Statistics::StatisticOutput
using fieldType_t = StatisticFieldInfo::fieldType_t
using fieldHandle_t = StatisticFieldInfo::fieldHandle_t
using FieldInfoArray_t = std::vector< StatisticFieldInfo * >
using FieldNameMap_t = std::unordered_map< std::string, fieldHandle_t >
Static Public Member Functions inherited from SST::Statistics::StatisticOutput
static const std::vector< SST::ElementInfoParam > & ELI_getParams ()
Detailed Description
The class for statistics output to a comma separated file.
Member Function Documentation
checkOutputParameters()
bool SST::Statistics::StatisticOutputCSV::checkOutputParameters () override protected virtual
Perform a check of provided parameters.
Returns
True if all required parameters and options are acceptable
Implements SST::Statistics::StatisticOutput.
References SST::Params::find(), and SST::Statistics::StatisticOutput::getOutputParameters().
endOfSimulation()
void SST::Statistics::StatisticOutputCSV::endOfSimulation () override protected virtual
Indicate to Statistic Output that simulation ended.
Statistic output may perform any shutdown code here as necessary.
Implements SST::Statistics::StatisticOutput.
implStartOutputEntries()
void SST::Statistics::StatisticOutputCSV::implStartOutputEntries (StatisticBase * statistic) override protected virtual
Implementation function for the start of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is about to send data to the Statistic Output for processing.
Parameters
statistic - Pointer to the statistic object than the output can retrieve data from.
Implements SST::Statistics::StatisticFieldsOutput.
References SST::Statistics::StatisticBase::getCompName(), SST::Statistics::StatisticFieldsOutput::getFieldInfoArray(), SST::Statistics::StatisticBase::getStatName(), SST::Statistics::StatisticBase::getStatSubId(), and SST::Statistics::StatisticBase::getStatTypeName().
implStopOutputEntries()
void SST::Statistics::StatisticOutputCSV::implStopOutputEntries () override protected virtual
Implementation function for the end of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is finished sending data to the Statistic Output for processing. The Statistic Output can perform any output related functions here.
Implements SST::Statistics::StatisticFieldsOutput.
References SST::Simulation_impl::getSimulation().
outputField()
void SST::Statistics::StatisticOutputCSV::outputField (fieldHandle_t fieldHandle, int32_t data) override protected
Implementation functions for output.
These will be called by the statistic to provide Statistic defined data to be output.
Parameters
fieldHandle - The handle to the registered statistic field.
data - The data related to the registered field to be output.
SST_ELI_REGISTER_DERIVED()
SST::Statistics::StatisticOutputCSV::SST_ELI_REGISTER_DERIVED (StatisticOutput , StatisticOutputCSV , "sst" , "statoutputcsv" , SST_ELI_ELEMENT_VERSION(1, 0, 0) , "Output directly to console screen") &
Construct a StatOutputCSV.
Parameters
outputParameters - Parameters used for this Statistic Output
startOfSimulation()
void SST::Statistics::StatisticOutputCSV::startOfSimulation () override protected virtual
Indicate to Statistic Output that simulation started.
Statistic output may perform any startup code here as necessary.
Implements SST::Statistics::StatisticOutput.
References SST::Statistics::StatisticFieldsOutput::getFieldInfoArray(), SST::Statistics::StatisticFieldInfo::getFieldName(), SST::Statistics::StatisticFieldInfo::getFieldType(), SST::Statistics::StatisticFieldsOutput::getFieldTypeShortName(), SST::Simulation_impl::getRank(), and SST::Simulation_impl::getSimulation().
The documentation for this class was generated from the following files:
src/sst/core/statapi/statoutputcsv.h
src/sst/core/statapi/statoutputcsv.cc