SST: SST::Core::ConfigGraphOutput Class Reference
SST::Core::ConfigGraphOutput Class Reference abstract
Public Member Functions
ConfigGraphOutput (const char *path)
virtual void generate (const Config *cfg, ConfigGraph *graph)=0
Protected Member Functions
std::vector< std::string > getParamsLocalKeys (const Params &params) const
Get a vector of the local keys.
std::vector< std::string > getSubscribedGlobalParamSets (const Params &params) const
Get a vector of the global param sets this Params object is subscribed to.
Static Protected Member Functions
static std::map< std::string, std::string > getGlobalParamSet (const std::string &name)
Get a named global parameter set.
static std::vector< std::string > getGlobalParamSetNames ()
Get a vector of the names of available global parameter sets.
Protected Attributes
FILE * outputFile
Member Function Documentation
getGlobalParamSet()
static std::map<std::string, std::string> SST::Core::ConfigGraphOutput::getGlobalParamSet (const std::string & name) inline static protected
Get a named global parameter set.
Parameters
name Name of the set to get
Returns
returns a copy of the reqeusted global param set
References SST::Params::getGlobalParamSet().
getGlobalParamSetNames()
static std::vector<std::string> SST::Core::ConfigGraphOutput::getGlobalParamSetNames () inline static protected
Get a vector of the names of available global parameter sets.
Returns
returns a vector of the names of available global param sets
References SST::Params::getGlobalParamSetNames().
getParamsLocalKeys()
std::vector<std::string> SST::Core::ConfigGraphOutput::getParamsLocalKeys (const Params & params) const inline protected
Get a vector of the local keys.
Returns
returns a vector of the local keys in this Params object
References SST::Params::getLocalKeys().
getSubscribedGlobalParamSets()
std::vector<std::string> SST::Core::ConfigGraphOutput::getSubscribedGlobalParamSets (const Params & params) const inline protected
Get a vector of the global param sets this Params object is subscribed to.
Returns
returns a vector of the global param sets his Params object is subscribed to
References SST::Params::getSubscribedGlobalParamSets().
The documentation for this class was generated from the following file:
src/sst/core/configGraphOutput.h