SST: SST::ThreadSyncDirectSkip Class Reference
SST::ThreadSyncDirectSkip Class Reference
Public Member Functions
ThreadSyncDirectSkip (int num_threads, int thread, Simulation_impl *sim)
Create a new ThreadSync object.
void setMaxPeriod (TimeConverter *period)
void before () override
void after () override
void execute (void) override
void processLinkUntimedData () override
Cause an exchange of Untimed Data to occur.
void finalizeLinkConfigurations () override
Finish link configuration.
void prepareForComplete () override
SimTime_t getNextSyncTime () override
void registerLink (const std::string &UNUSED(name), Link *UNUSED(link)) override
Register a Link which this Sync Object is responsible for.
ActivityQueue * registerRemoteLink (int UNUSED(id), const std::string &UNUSED(name), Link *UNUSED(link)) override
uint64_t getDataSize () const
Public Member Functions inherited from SST::ThreadSync
void setMaxPeriod (TimeConverter *period)
TimeConverter * getMaxPeriod ()
virtual void registerLink (const std::string &name, Link *link)=0
Register a Link which this Sync Object is responsible for.
virtual ActivityQueue * registerRemoteLink (int tid, const std::string &name, Link *link)=0
Additional Inherited Members
Protected Member Functions inherited from SST::ThreadSync
void finalizeConfiguration (Link *link)
void prepareForCompleteInt (Link *link)
void sendUntimedData_sync (Link *link, Event *data)
void setLinkDeliveryInfo (Link *link, uintptr_t info)
Link * getDeliveryLink (Event *ev)
Protected Attributes inherited from SST::ThreadSync
SimTime_t nextSyncTime
TimeConverter * max_period
Constructor & Destructor Documentation
ThreadSyncDirectSkip()
SST::ThreadSyncDirectSkip::ThreadSyncDirectSkip (int num_threads, int thread, Simulation_impl * sim)
Create a new ThreadSync object.
Create a new ThreadSyncDirectSkip object.
References SST::Simulation_impl::getNumRanks(), SST::Simulation_impl::getRank(), and SST::Core::ThreadSafe::Barrier::resize().
The documentation for this class was generated from the following files:
src/sst/core/sync/threadSyncDirectSkip.h
src/sst/core/sync/threadSyncDirectSkip.cc